"""
Active Brownian Particle in 2D
"""

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import Normalize
from matplotlib.cm import ScalarMappable

from aleatory.processes.base import StochasticProcess
from aleatory.utils.utils import get_times
from aleatory.utils.plotters_2d import plot_coordinate_paths


class ABP2D(StochasticProcess):
    r"""

    Active Brownian Particle in Two Dimensions
    ==========================================

    Notes
    -----

    An active Brownian particle in two dimensions is a stochastic process
    with position and orientation, where the particle undergoes self-propelled
    motion at constant speed while its heading evolves diffusively.

    In this implementation, the process
    :math:`\{(X_t, Y_t, \theta_t) : t \geq 0\}` satisfies the Langevin system

    .. math::

       \dot{X}_t
       =
       v \cos(\theta_t)
       +
       \sqrt{2 D_{\mathrm{T}}}\,\eta_x(t)

    .. math::

       \dot{Y}_t
       =
       v \sin(\theta_t)
       +
       \sqrt{2 D_{\mathrm{T}}}\,\eta_y(t)

    .. math::

       \dot{\theta}_t
       =
       \sqrt{2 D_{\mathrm{R}}}\,\eta_\theta(t)

    where :math:`v` is the self-propulsion speed,
    :math:`D_{\mathrm{T}}` is the translational diffusion coefficient,
    :math:`D_{\mathrm{R}}` is the rotational diffusion coefficient, and
    :math:`\eta_x`, :math:`\eta_y`, and :math:`\eta_\theta` are independent
    Gaussian white noises.

    Thus the particle moves persistently over short times, but gradually loses
    memory of its initial direction due to rotational diffusion.

    When :math:`D_{\mathrm{T}} = 0`, the randomness enters only through the
    orientation process. When :math:`D_{\mathrm{R}} = 0`, the motion reduces
    to deterministic ballistic transport along a fixed direction.

    The sample paths are generated by an Euler discretisation of the Langevin
    equations over a finite interval :math:`[0,T]`.

    The planar sample returned by :meth:`sample` consists of the coordinate
    pair :math:`(X_t,Y_t)`. The most recently simulated orientation path is
    stored on the instance and may be accessed via the :attr:`last_theta`
    property, or returned explicitly using :meth:`sample_with_orientation`.

    Constructor, Methods, and Attributes
    ------------------------------------

    """
    def __init__(
        self,
        speed=1.0,
        rotational_diffusion=1.0,
        translational_diffusion=0.0,
        T=1.0,
        x0=0.0,
        y0=0.0,
        theta0=0.0,
        rng=None,
    ):
        super().__init__(T=T, rng=rng)

        if speed < 0.0:
            raise ValueError("speed must be non-negative")
        if rotational_diffusion < 0.0:
            raise ValueError("rotational_diffusion must be non-negative")
        if translational_diffusion < 0.0:
            raise ValueError("translational_diffusion must be non-negative")

        self.speed = speed
        self.rotational_diffusion = rotational_diffusion
        self.translational_diffusion = translational_diffusion
        self.x0 = x0
        self.y0 = y0
        self.theta0 = theta0
        self.name = (
            "Active Brownian Particle "
            rf"$(v_0={self.speed},\ D_{{\mathrm{{T}}}}={self.translational_diffusion},\ D_{{\mathrm{{R}}}}={self.rotational_diffusion})$"
        )
        self.n = None
        self.times = None
        self._last_theta = None
        self._last_x = None
        self._last_y = None


    def __str__(self):
        return (
            f"Active Brownian Particle with "
            f"speed={self.speed}, rotational_diffusion={self.rotational_diffusion}, translational_diffusion={self.translational_diffusion}"
        )


    def __repr__(self):
        return (
            f"ABP2D("
            f"speed={self.speed}, "
            f"rotational_diffusion={self.rotational_diffusion}, "
            f"translational_diffusion={self.translational_diffusion}, "
            f"T={self.T}, "
            f"x0={self.x0}, "
            f"y0={self.y0}, "
            f"theta0={self.theta0}"
            f")"
        )

    def metadata(self):
        return {
            "class": self.__class__.__name__,
            "repr": repr(self),
            "speed": self.speed,
            "rotational_diffusion": self.rotational_diffusion,
            "translational_diffusion": self.translational_diffusion,
            "T": self.T,
            "x0": self.x0,
            "y0": self.y0,
            "theta0": self.theta0,
        }

    @property
    def last_theta(self):
        """Most recently simulated orientation path."""
        return self._last_theta


    @property
    def last_position(self):
        """Most recently simulated planar path as a pair ``(x, y)``."""
        if self._last_x is None or self._last_y is None:
            return None
        return self._last_x, self._last_y


    def _sample(self, n):
        if n < 2:
            raise ValueError("dimension n must be at least 2")

        dt = self.T / (n - 1)

        theta_noise = self.rng.normal(
            loc=0.0,
            scale=np.sqrt(2.0 * self.rotational_diffusion * dt),
            size=n - 1,
        )

        theta = np.empty(n)
        theta[0] = self.theta0
        theta[1:] = self.theta0 + np.cumsum(theta_noise)

        dx_active = self.speed * np.cos(theta[:-1]) * dt
        dy_active = self.speed * np.sin(theta[:-1]) * dt

        if self.translational_diffusion > 0.0:
            dx_noise = self.rng.normal(
                loc=0.0,
                scale=np.sqrt(2.0 * self.translational_diffusion * dt),
                size=n - 1,
            )
            dy_noise = self.rng.normal(
                loc=0.0,
                scale=np.sqrt(2.0 * self.translational_diffusion * dt),
                size=n - 1,
            )
        else:
            dx_noise = np.zeros(n - 1)
            dy_noise = np.zeros(n - 1)

        x = np.empty(n)
        y = np.empty(n)
        x[0] = self.x0
        y[0] = self.y0
        x[1:] = self.x0 + np.cumsum(dx_active + dx_noise)
        y[1:] = self.y0 + np.cumsum(dy_active + dy_noise)

        self._last_theta = theta
        self._last_x = x
        self._last_y = y
        return x, y


    def sample(self, n):
        self.n = n
        self.times = get_times(self.T, n)
        return self._sample(n)


    def sample_with_orientation(self, n):
        self.n = n
        self.times = get_times(self.T, n)
        x, y = self._sample(n)
        return x, y, self._last_theta.copy()


    def simulate(self, n, N):
        self.n = n
        self.times = get_times(self.T, n)
        simulations = []
        for _ in range(N):
            x, y = self._sample(n)
            simulations.append((x, y))
        return simulations


    def simulate_with_orientation(self, n, N):
        self.n = n
        self.times = get_times(self.T, n)
        simulations = []
        for _ in range(N):
            x, y = self._sample(n)
            simulations.append((x, y, self._last_theta.copy()))
        return simulations


    def plot_sample(
            self,
            n,
            coordinates=False,
            title=None,
            suptitle=None,
            mode="linear",
            ax=None,
            **fig_kw,
    ):
        if coordinates:
            return self.plot_sample_coordinates(
                n=n,
                title=title,
                suptitle=suptitle,
                mode=mode,
                ax=ax,
                **fig_kw,
            )
        return self.plot_sample_2d(
            n=n,
            title=title,
            suptitle=suptitle,
            ax=ax,
            **fig_kw
        )


    def plot_sample_coordinates(
            self,
            n,
            title=None,
            suptitle=None,
            mode="linear",
            ax=None,
            **fig_kw,
    ):
        chart_suptitle = suptitle if suptitle is not None else self.name
        x, y, _ = self.sample_with_orientation(n)

        ax = plot_coordinate_paths(
            times=self.times,
            paths1=[x],
            paths2=[y],
            title=title,
            suptitle=chart_suptitle,
            mode=mode,
            ax=ax,
            **fig_kw,
        )
        return ax


    def plot_sample_2d(
            self,
            n,
            title=None,
            suptitle=None,
            color_by="time",
            ax=None,
            show_colorbar=True,
            **fig_kw,
    ):
        cmap = plt.get_cmap()
        chart_suptitle = suptitle if suptitle is not None else self.name
        x, y, _ = self.sample_with_orientation(n)

        if color_by == "time":
            values = self.times
            norm = Normalize(vmin=values.min(), vmax=values.max())
            colors_indices = cmap(norm(values))
            label_title = "Time"
        elif color_by == "distance":
            values = np.sqrt((x - self.x0) ** 2 + (y - self.y0) ** 2)
            norm = Normalize(vmin=values.min(), vmax=values.max())
            colors_indices = cmap(norm(values))
            label_title = "Distance to initial position"
        else:
            raise ValueError("color_by must be either 'time' or 'distance'")

        created_fig = False

        if ax is None:
            fig, ax = plt.subplots(**fig_kw)
            created_fig = True
        else:
            fig = ax.figure

        start_color = colors_indices[0]
        end_color = colors_indices[-1]
        marker_edgecolor = plt.rcParams["axes.edgecolor"]

        ax.scatter(
            x[0], y[0],
            color=start_color,
            edgecolor=marker_edgecolor,
            linewidth=0.6,
            label="Start",
            zorder=5,
        )

        ax.scatter(
            x[-1], y[-1],
            color=end_color,
            edgecolor=marker_edgecolor,
            linewidth=0.6,
            label="End",
            zorder=5,
        )

        for i in range(len(x) - 1):
            ax.plot(x[i:i + 2], y[i:i + 2], color=colors_indices[i], lw=1.5)

        if show_colorbar:
            fig.colorbar(
                ScalarMappable(norm=norm, cmap=cmap),
                label=label_title,
                ax=ax,
            )

        if created_fig and suptitle is not False:
            fig.suptitle(chart_suptitle)

        ax.set_title(title)
        ax.set_xlabel("$X_1(t)$")
        ax.set_ylabel("$X_2(t)$")
        ax.legend()
        ax.grid(True)
        ax.axis("equal")

        fig = ax.figure
        existing_metadata = getattr(fig, "_aleatory_metadata", None)
        if existing_metadata is None:
            fig._aleatory_metadata = {"sources": []}

        fig._aleatory_metadata["sources"].append(self.metadata())

        return ax
